### ISSUE TITLE
wtd_system_update_needs_reboot is not registered for Fedora run

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-system-update#10]
### Type of Report

bug

### Actual behaviour

Fedora run fails on task "Reboot Machine" as wtd_system_update_needs_reboot is not defined

### Expected behaviour

wtd_system_update_needs_reboot should be set to a reasonable default for the Fedora run.

**Comment by daniel-wtd** [comment]
meh, dang ^^
