### ISSUE TITLE
remove not needed dependency: yum

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-system-update#8]
### Type of Report

bug

### Actual behaviour

depends on role yum

### Expected behaviour

not needed

**Comment by daniel-wtd** [comment]
After reviewing the role I found that yum-utils is actually needed for the "needs restarting" feature.

I think the best approach will be to refactor the role a bit:

- Remove dependencies
- Add hook for centos/redhat
- put in packages via centos.yml

@donvipre 
Do you think this is reasonable?

I think this will allow extensions for future support of other OS.

**Comment by donvipre** [comment]
yes, this is a nice approach

**Comment by daniel-wtd** [comment]
started proceeding
